# Generated by Django 2.2.5 on 2019-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKayit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
    ]
